name: rickandmorty
recipe: laravel
config:
  webroot: src/public
  php: '7.4'
  via: nginx
  database: mariadb
  xdebug: true

services:
  phpmyadmin:
    type: phpmyadmin:5.0
    hosts:
      - database